# Generated by Django 3.2.5 on 2021-07-12 01:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('iluminacao', models.IntegerField()),
                ('umidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200, unique=True)),
                ('umi_manual', models.IntegerField(blank=True, null=True)),
                ('ilu_manual', models.IntegerField(blank=True, null=True)),
                ('ilu_dados', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('umi_dados', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('ts_dados', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, size=None)),
                ('especie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='epecie_plantada', to='planta.especie')),
            ],
        ),
    ]
