# Generated by Django 3.2.5 on 2021-07-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='descricao',
        ),
    ]
