# Generated by Django 3.2.5 on 2021-07-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_remove_especie_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epecie_plantada', to='planta.especie'),
        ),
    ]
